### ISSUE TITLE
Please run CI with more dmd versions

### ISSUE THREAD

**Issue by SingingBush** [atilaneves/unit-threaded#249]
for projects that use unit-threaded that support a wide amount of compiler releases it would be handy if this projects CI was running against more versions of dmd. 

I'm running builds from dmd 2.080 to 2.096 and some of the older versions are failing. If you don't wish to support versions that far back then please at least support last a defined range of compilers and make it clear in the readme.

With dmd 2.081.1 and 2.082.1 on Ubuntu I'm seeing:

```
unit-threaded:from 1.0.15: building configuration "library"...
unit-threaded:exception 1.0.15: building configuration "library"...
unit-threaded:assertions 1.0.15: building configuration "library"...
unit-threaded:integration 1.0.15: building configuration "library"...
unit-threaded:mocks 1.0.15: building configuration "library"...
unit-threaded:property 1.0.15: building configuration "default"...
unit-threaded:runner 1.0.15: building configuration "library"...
../../../.dub/packages/unit-threaded-1.0.15/unit-threaded/subpackages/runner/source/unit_threaded/runner/runner.d(102,35): Error: found `,` when expecting `)`
../../../.dub/packages/unit-threaded-1.0.15/unit-threaded/subpackages/runner/source/unit_threaded/runner/runner.d(102,37): Error: found `module_` when expecting `;`
../../../.dub/packages/unit-threaded-1.0.15/unit-threaded/subpackages/runner/source/unit_threaded/runner/runner.d(102,44): Error: found `,` instead of statement
../../../.dub/packages/unit-threaded-1.0.15/unit-threaded/subpackages/runner/source/unit_threaded/runner/runner.d(103,34): Error: found `,` when expecting `)`
../../../.dub/packages/unit-threaded-1.0.15/unit-threaded/subpackages/runner/source/unit_threaded/runner/runner.d(103,36): Error: found `".testData()"` when expecting `;` following statement
../../../.dub/packages/unit-threaded-1.0.15/unit-threaded/subpackages/runner/source/unit_threaded/runner/runner.d(103,49): Error: found `)` instead of statement
/opt/hostedtoolcache/dc/dmd-2.082.1/x64/dmd2/linux/bin64/dmd failed with exit code 1.
Error: Process completed with exit code 2.
```

With dmd 2.080.1 on Ubuntu I'm seeing

```
Performing "debug" build using /opt/hostedtoolcache/dc/dmd-2.080.1/x64/dmd2/linux/bin64/dmd for x86_64.
unit-threaded:from 1.0.15: building configuration "library"...
unit-threaded:exception 1.0.15: building configuration "library"...
unit-threaded:assertions 1.0.15: building configuration "library"...
unit-threaded:integration 1.0.15: building configuration "library"...
unit-threaded:mocks 1.0.15: building configuration "library"...
unit-threaded:property 1.0.15: building configuration "default"...
../../../.dub/packages/unit-threaded-1.0.15/unit-threaded/subpackages/property/source/unit_threaded/randomized/random.d(52,11): Error: statement expected to be `{ }`, not `(`
../../../.dub/packages/unit-threaded-1.0.15/unit-threaded/subpackages/property/source/unit_threaded/randomized/random.d(53,9): Error: found `do` when expecting `;` following statement
../../../.dub/packages/unit-threaded-1.0.15/unit-threaded/subpackages/property/source/unit_threaded/randomized/random.d(54,5): Error: missing `do { ... }` after `in` or `out`
/opt/hostedtoolcache/dc/dmd-2.080.1/x64/dmd2/linux/bin64/dmd failed with exit code 1.
Error: Process completed with exit code 2.
```

**Comment by atilaneves** [comment]
This ended up being more involved than I thought and I worked around it by deleting or commenting out test code that failed as a result. 

I've pushed an `old-dmd-support` branch that you should be able to use from dub.

The versions supported are what's in CI. I could add them to the README but that'll mean remembering to always update it, which I won't and therefore it'll end up lying.

**Comment by SingingBush** [comment]
thanks for the branch. I made a fork and took a look at getting a decent build matrix going. Seems that the current codebase should be ok on D versions 2.089 to latest (2.096). I would have made a pull request for [this branch](https://github.com/SingingBush/unit-threaded/tree/ci/multiple_compilers) but there's still the odd problem. Generally on LDC:

| Compiler      | Ubuntu | Windows | Mac |
| ----------- | ----------- | ----------- | ----------- |
| dmd-latest (2.096.1)   | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| dmd-2.095.1  | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| dmd-2.094.2  | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| dmd-2.093.1  | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| dmd-2.092.1  | :heavy_check_mark: | :x: | :heavy_check_mark: |
| dmd-2.091.1  | :heavy_check_mark: | :x: | :heavy_check_mark: |
| dmd-2.090.1  | :heavy_check_mark: | :x: | :heavy_check_mark: |
| dmd-2.089.1  | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| ldc-latest  | :x: | :heavy_check_mark: | :x: |
| ldc-25  | :x: | :heavy_check_mark: | :x: |
| ldc-24  | :x: | :heavy_check_mark: | :x: |
| ldc-23  | :x: | :heavy_check_mark: | :x: |

The ldc builds could probably be sorted easy as it just seems to be looking for dmd for some reason:

```
Regular tests
--------------------

unit_threaded.exception.UnitTestException@tests/unit_threaded/ut/integration.d(103): Could not execute `dmd /Users/runner/work/unit-threaded/unit-threaded/tmp/unit-threaded/YYYYYYILKqr3/hello.d`:
Executable file not found: dmd
----------------
```

On Windows I was seeing linker errors:

```
Issue 61
Performing "unittest" build using C:\hostedtoolcache\windows\dc\dmd-2.091.1\x64\dmd2\windows\bin\dmd.exe for x86_64.
unit-threaded:from ~ci/multiple_compilers: building configuration "library"...
unit-threaded:exception ~ci/multiple_compilers: building configuration "library"...
unit-threaded:assertions ~ci/multiple_compilers: building configuration "library"...
unit-threaded:integration ~ci/multiple_compilers: building configuration "library"...
unit-threaded:mocks ~ci/multiple_compilers: building configuration "library"...
unit-threaded:property ~ci/multiple_compilers: building configuration "default"...
unit-threaded:runner ~ci/multiple_compilers: building configuration "library"...
unit-threaded ~ci/multiple_compilers: building configuration "library"...
issue61 ~master: building configuration "application"...
Linking...
issue61.obj : fatal error LNK1179: invalid or corrupt file: duplicate COMDAT '_D3std6traits__T6fqnSymS3foo3barZ11adjustIdentFAyaZQe'
Error: linker exited with status 1179
C:\hostedtoolcache\windows\dc\dmd-2.091.1\x64\dmd2\windows\bin\dmd.exe failed with exit code 1.
Error: Process completed with exit code 1.
```

**Comment by atilaneves** [comment]
PRs welcome.
