### PR TITLE
resolves #249 run CI with multiple compiler versions (2.089 to 2.096)

### LINKED ISSUE #249: Please run CI with more dmd versions
for projects that use unit-threaded that support a wide amount of compiler releases it would be handy if this projects CI was running against more versions of dmd. 

I'm running builds from dmd 2.080 to 2.096 and some of the older versions are failing. If you don't wish to support versions that far back then please at least support last a defined range of compilers and make it clear in the readme.

With dmd 2.081.1 and 2.082.1 on Ubuntu I'm seeing:

```
unit-threaded:from 1.0.15: building configuration "library"...
unit-threaded:exception 1.0.15: building configuration "library"...
unit-threaded:assertions 1.0.15: building configuration "library"...
unit-threaded:integration 1.0.15: building configuration "library"...
unit-threaded:mocks 1.0.15: building configuration "library"...
unit-threaded:property 1.0.15: building configuration "default"...
unit-threaded:runner 1.0.15: building configuration "library"...
../../../.dub/packages/unit-threaded-1.0.15/unit-threaded/subpackages/runner/source/unit_threaded/runner/runner.d(102,35): Error: found `,` when expecting `)`
../../../.dub/packages/unit-threaded-1.0.15/unit-threaded/subpackages/runner/source/unit_threaded/runner/runner.d(102,37): Error: found `module_` when expecting `;`
../../../.dub/packages/unit-threaded-1.0.15/unit-threaded/subpackages/runner/source/unit_threaded/runner/runner.d(102,44): Error: found `,` instead of statement
../../../.dub/packages/unit-threaded-1.0.15/unit-threaded/subpackages/runner/source/unit_threaded/runner/runner.d(103,34): Error: found `,` when expecting `)`
../../../.dub/packages/unit-threaded-1.0.15/unit-threaded/subpackages/runner/source/unit_threaded/runner/runner.d(103,36): Error: found `".testData()"` when expecting `;` following statement
../../../.dub/packages/unit-threaded-1.0.15/unit-threaded/subpackages/runner/source/unit_threaded/runner/runner.d(103,49): Error: found `)` instead of statement
/opt/hostedtoolcache/dc/dmd-2.082.1/x64/dmd2/linux/bin64/dmd failed with exit code 1.
Error: Process completed with exit code 2.
```

With dmd 2.080.1 on Ubuntu I'm seeing

```
Performing "debug" build using /opt/hostedtoolcache/dc/dmd-2.080.1/x64/dmd2/linux/bin64/dmd for x86_64.
unit-threaded:from 1.0.15: building configuration "library"...
unit-threaded:exception 1.0.15: building configuration "library"...
unit-threaded:assertions 1.0.15: building configuration "library"...
unit-threaded:integration 1.0.15: building configuration "library"...
unit-threaded:mocks 1.0.15: building configuration "library"...
unit-threaded:property 1.0.15: building configuration "default"...
../../../.dub/packages/unit-threaded-1.0.15/unit-threaded/subpackages/property/source/unit_threaded/randomized/random.d(52,11): Error: statement expected to be `{ }`, not `(`
../../../.dub/packages/unit-threaded-1.0.15/unit-threaded/subpackages/property/source/unit_threaded/randomized/random.d(53,9): Error: found `do` when expecting `;` following statement
../../../.dub/packages/unit-threaded-1.0.15/unit-threaded/subpackages/property/source/unit_threaded/randomized/random.d(54,5): Error: missing `do { ... }` after `in` or `out`
/opt/hostedtoolcache/dc/dmd-2.080.1/x64/dmd2/linux/bin64/dmd failed with exit code 1.
Error: Process completed with exit code 2.
```

### PR DESCRIPTION
**Pull request by SingingBush**
I got the changes in so that CI runs against a variety of compilers and platforms:

| Compiler      | Ubuntu | Windows | Mac |
| ----------- | ----------- | ----------- | ----------- |
| dmd-latest (2.096.1)   | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| dmd-2.095.1  | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| dmd-2.094.2  | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| dmd-2.093.1  | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| dmd-2.092.1  | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| dmd-2.091.1  | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| dmd-2.090.1  | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| dmd-2.089.1  | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| ldc-latest  | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| ldc-25  | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| ldc-24  | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| ldc-23  | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |

### CODE REVIEW

**Comment by aminya** [comment]
Appveyor and Travis should be probably removed.

**Comment by SingingBush** [comment]
@atilaneves I'm in agreement with aminya that the Appveyor /travis builds should be dropped. The Github CI is fast, relaible, easy to use, well documented, and fully integrated with github. I can look at making further changes to remove them with this PR or leave as it is. Any preference?

**Comment by atilaneves** [comment]
Rebase after https://github.com/atilaneves/unit-threaded/pull/252 gets merged and the appveyor problem goes away.

**Comment by SingingBush** [comment]
thanks, rebased now

**Review by atilaneves — APPROVED** [review]
