### ISSUE TITLE
isEqual cannot compare a slice to a static array

### ISSUE THREAD

**Issue by joseph-wakeling-frequenz** [atilaneves/unit-threaded#212]
Simple example unittest:

```D
unittest
{
    import unit_threaded.assertions : should;
    float[] lhs = [2f, 4, 6, 8, 10, 12];
    float[6] rhs = [2f, 4, 6, 8, 10, 12];

    lhs.should == rhs;
}
```

This works fine with unit-threaded v0.10.8 and earlier, but fails with v1.0.0 and later (tested with compiler LDC 1.20.1, frontend 2.090.1):

```
../../../.dub/packages/unit-threaded-1.0.4/unit-threaded/subpackages/assertions/source/unit_threaded/assertions.d(52,17): Error: template unit_threaded.assertions.isEqual cannot deduce function from argument types !()(float[], float[6]), candidates are:
../../../.dub/packages/unit-threaded-1.0.4/unit-threaded/subpackages/assertions/source/unit_threaded/assertions.d(551,6):        isEqual(V, E)(auto ref V value, auto ref E expected)
  with V = float[],
       E = float[6]
  must satisfy the following constraint:
       !isInputRange!V
../../../.dub/packages/unit-threaded-1.0.4/unit-threaded/subpackages/assertions/source/unit_threaded/assertions.d(563,6):        isEqual(V, E)(in V value, in E expected)
  with V = float[],
       E = float[6]
  must satisfy the following constraint:
       isAssociativeArray!V
../../../.dub/packages/unit-threaded-1.0.4/unit-threaded/subpackages/assertions/source/unit_threaded/assertions.d(604,6):        isEqual(V, E)(scope V value, scope E expected)
  with V = float[],
       E = float[6]
  must satisfy the following constraint:
       isInputRange!E
../../../.dub/packages/unit-threaded-1.0.4/unit-threaded/subpackages/assertions/source/unit_threaded/assertions.d(618,6):        isEqual(V, E)(scope V value, scope E expected)
  with V = float[],
       E = float[6]
  must satisfy the following constraint:
       isSomeString!V
../../../.dub/packages/unit-threaded-1.0.4/unit-threaded/subpackages/assertions/source/unit_threaded/assertions.d(635,6):        isEqual(V, E)(scope V value, scope E expected)
  with V = float[],
       E = float[6]
  must satisfy the following constraint:
       isObject!V
../../../.dub/packages/unit-threaded-1.0.4/unit-threaded/subpackages/assertions/source/unit_threaded/assertions.d(1009,24): Error: template instance unit_threaded.assertions.shouldEqual!(float[], float[6]) error instantiating
```

Obviously it's easy to work around -- just use `lhs.should == rhs[];` -- but it feels unintuitive that the comparison would fail.  Is this intended behaviour, or a bug in the changes to template overloads?

Either way it's a result of the changes in this PR: https://github.com/atilaneves/unit-threaded/pull/188 and specifically in this commit: 5d7800d7d9ca16d9bb4fac7482094873a50451ae.

**Comment by joseph-wakeling-frequenz** [comment]
Thanks very much @atilaneves!
